oxc_image: xcode8
language: objective-c
xcode-project: GitHub.xcworkspace
xcode_scheme: GitHub
xcode_sdk: iphonesimulator8.4
script:
    - xcodebuild -scheme 'GitHub-iOS' -sdk iphonesimulator CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO test | xcpretty -c
    - xcodebuild -scheme 'GitHub-OSX' test | xcpretty -c